name: Frontend template deploy

on:
  push:
    branches: master
    paths: templates/frontend/**

jobs:
  update_static_folder:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}
          
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.NEAT_CLI_PRIVATE_KEY }}

      - name: Build files
        run: |
          yarn global add ssh://git@github.com:neattech-io/neat#master
          cd templates/frontend/
          yarn || true
          yarn build

      - name: Upload files via SSH
        uses: appleboy/scp-action@master
        with:
          host: '104.248.31.56'
          username: 'root'
          key_path: ./ssh_keys/neat
          rm: true
          source: "templates/frontend/dist"
          target: '/var/www/static/neat-docs'
          strip_components: 2
